# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - master
      - add-workflow-actions
  pull_request:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up calibre
        uses: docker://talebook/calibre:3.8

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest  pyqt5==5.15.3
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 webserver --count --select=E9,F63,F7,F82 --show-source --statistics

          # exit-zero treats all errors as warnings
          flake8 webserver --count --exit-zero --statistics --config .style.yapf

      - name: Test with pytest
        run: |
          pytest ./tests
